











* Wall
* Quakelive_Bible



Motivation, Attitude (Pushing the limits) *by chance

It's important to keep a healthy morale when you go to play a game. Sometimes
you just aren't motivated. If you're not feeling up to a game, don't play. It
takes discipline just to take a break sometimes. A lot of players think, "Man,
I keep losing because I'm playing bad... I'm playing badly because I don't feel
like playing... but I need to get better so I have to keep playing." This is a
vicious cycle that traps almost every aspiring pro*** at some point. If you
find yourself in that situation you just need to remind yourself that it's the
quality that counts.

Taking into account the stress of tournaments, it may all be a bit overwhelming
at times. If you're new to the scene, you might be freaking out months before
the tournament even starts. If you take my previous advice, you know its not
smart to practice when you're stressed because you'll be too emotional to
concentrate or play your best. So how will you get practice if you're purposely
not playing because the pressure is too high? The answer is simple. Do what you
can with what you have, and, you receive what you give.

"Do what you can with what you have." What I mean by this is, you do as much as
you can with what you're given. Whatever that means, whatever situation you are
in. If you're stressed out and you can't seem to calm down, you have may have
no choice but to play through it. You gotta accept that you're just going to
suck while you play. If you can't practice for a solid week before an event,
what can you do about it? Do everything you can but don't resist it
psychologically. You have to bring peace into the game in order to maintain
functionality because....

"You receive what you give." Give it nothing, you can expect to receive
nothing. Give it your all, every, single, time-- you're going to get something
back. If it's not enough for you, too bad - give it some more. How is there a
choice in the matter? And don't just give it more- give it better, brighter.
Give it lightness, freedom, joy, enthusiasm. See what you get back. Life is the
journey, a beautiful means through uncertainty. So you start with what you
have, and you do what you can with it. Give it your all, Good luck.
Â 
source www.myeg.net
Write_a_comment

0 Comments


*  loading


* Introduction
* Discipline
* Presence
* Opponent_Awareness/Enemy_Status.
* Resource_Timing
* Aim
* Motivation,_Attitude
* Resolve.
* DM14_-_Grim_Dungeons
* OSPDM5_-_Deep_Inside
* Unity's_personal_guide

Â 
Â 
Â 
Â 
Â 


          _free_counters_


Imprint | _druckversion_print_version | Sitemap
 Jimdo_logout | Edit
