











* Wall
* Quakelive_Bible



Discipline. (Willing forward the strongest formula) *by chance

Create no waste. Discipline is probably the most difficult and synonymously
important strength of a competitor. Discipline is often what separates the
aforementioned soft practice junkies from the hardened veteran masters. The
practice junkie plays, and plays, and plays, but while he does so he'll be
thinking about doing his laundry. Or what about that new episode of Lost? A
thousand superfluous thoughts are floating through his head while he's
drunkenly dropping into the void like a bewildered klutz or missing the easy
jump pad rail. Players like Fatal1ty will tell you, even when you practice you
need to focus 100 percent on every game, the entire game. If you can keep this
up for 8 hours a day you're going to come out with some serious results. If you
can do that, by the way, you may have some kind of gift ;p. There are few
people I know that can play more than a couple hours without reaching "burn
out." Don't concern yourself too much with the quantity however, because the
quality is what counts.

So discipline is largely about staying focused, and staying focused has a lot
to do with your emotional state. You can't be getting too angry, excited, or
relaxed when you need to be completing a crucial task like timing red armor or
dodging behind a pillar. An example of the kind of excitement that creates
problems is when that energetic excited feeling takes your mind out of the
game. i.e. "I'm doing so good! That shot was amazing! Wait.. what was the armor
time again?" Herein lies the difference between an amateur and an expert. The
expert player will simply move onto the next frag, perhaps increasing or
maintaining the same level of energy and readiness whenever necessary.

All that matters is that at the very least you're ready to accept and deal with
the current situation, rather than acting on your emotions regarding the
current situation. On the whole, emotional features like excitement will, by
nature, lead to what are called "leaks." Unintentional holes in your game that,
despite knowing what you should have done in a situation, you went ahead and
did something else. Leaks commonly arise from emotion, but they may also come
in a more dangerously subtle package; thoughts. Anytime you have thoughts
floating around that don't pertain to the game at hand you generate leaks.
Disciplined athletes have little to no leaks.

In order to prevent leaks you have to be aware of your current state of mind.Â 
Keeping your mind clear of fog will allow you to take on any and all
information presented to you, and process it in an unbiased, no-nonsense
fashion.Â  With a clear mind, you stay out of your own way and focus on the
critical information you need to make your next move.Â  That is what strong
discipline is about and that is the core purpose of discipline.

Don't think of discipline as a strenuous exercise. A large part of it is making
yourself comfortable with giving it your all and ensuring you're ready to play
irregardless of what might have or could happen inside and outside of the game.
There is an "easy way" to attain a leak-free strong discipline without breaking
your routine down into thousands of meticulous details and then making yourself
remember them all when you need them. This leads us to our next insight.
Â 
source www.myeg.net
Write_a_comment

0 Comments


*  loading


* Introduction
* Discipline
* Presence
* Opponent_Awareness/Enemy_Status.
* Resource_Timing
* Aim
* Motivation,_Attitude
* Resolve.
* DM14_-_Grim_Dungeons
* OSPDM5_-_Deep_Inside
* Unity's_personal_guide

Â 
Â 
Â 
Â 
Â 


          _free_counters_


Imprint | _druckversion_print_version | Sitemap
 Jimdo_logout | Edit
