











* Wall
* Quakelive_Bible



Introduction *by chance

Practice, Practice, Practice. The famous words of Champion Johnathan "Fatal1ty"
Wendel. We've all heard it before, and we all know how important it is to
reaching the highest levels of play, but what about those guys who practice all
day every day and seem to never improve? I'm sure you know who I'm talking
about. That guy who's been playing for the last 4 years and in the 240 hours of
game time he's logged, since the Quake Live beta opened, has barely managed to
etch out a positive record. Well, this article intends to help those players -
and any player ready to patch up holes in their game that prevent them from
reaching higher levels of play. Unlike other articles, you won't find play by
play instructions here. Quake is about choices. From the second you spawn in,
every single thing you do matters. As we'll see more into this guide, even
every single thing you think about doing matters.

This article is structured around insight. Insights are the foundation for your
improvement; the building blocks of your game. They enable you to make the
right choices at the right times. Without them, you can't build a structure
strong enough to carry you into the next level. Remember that in every step
forward there is an often hidden insight holding it in place that you must find
in order to further establish it as your strength. Meaning, if you're playing
great - there's a reason why. You have to find that reason to retain that level
of play. If you're playing miserably, there's a reason why. You have find that
reason and stamp it out.

The following sections primarily contain insights to help you improve your game
on your own, this is the most important thing you can learn. You won't always
have someone to tell you how to play. Irregardless I cover a few key subjects
that should be your primary focus every time you play. Those two subjects are
enemy status and timing. We'll get to them a little later. For now, we need to
understand some principles to keep your head together.
Â 
source www.myeg.net
Write_a_comment

0 Comments


*  loading


* Introduction
* Discipline
* Presence
* Opponent_Awareness/Enemy_Status.
* Resource_Timing
* Aim
* Motivation,_Attitude
* Resolve.
* DM14_-_Grim_Dungeons
* OSPDM5_-_Deep_Inside
* Unity's_personal_guide

Â 
Â 
Â 
Â 
Â 


          _free_counters_


Imprint | _druckversion_print_version | Sitemap
 Jimdo_logout | Edit
