












* Wall
* Quakelive_Bible

Sun
19
Sep
2010


A_chat_with_PerpetualWar_!

I had a nice chat with PerpetualWar about dothedk.com .
Â 
First of all thanks PerpetualWar for your feedback !
Â 
He gave me some nice input, ideas and asked me some questions wich im going to
answer from time to time !
Â 
The plan at the moment is adding every week a new tactic guide.
There are 11 maps at the moment for TDM ( with 2v2 maps ) .Â 
Â 
From time to time i will go deeper and deeper in those guides.
Recognize that i cant and wont go in EVERY situation.
Its to much !
Â 
TDM is something about feeling, experience and of course knowledge what you get
from time to time.
Â 
I try to go as much as possible in standard situations.
Things like, when start to rush, when to stop, what about the important
positions, what happens if we are 20 Frags behind, how important are
communications for the game, what kind of informations are important, what is
the key of a good working team.
Â 
I am not sure how and when ... but this is more or less the "plan" :-)
Â 
Â 
If someone has ideas, suggestions, questions etc. feel free to email
Â 
mail [ a t ] dothedk dot com
Â 
dash, JoCKo or me ( or probably someone else who is going to help here ) are
trying to add or answer it !
Â 
Â 
Â 
Trackback_URL_for_this_article

Trackbacks / Pingbacks 0

Write_a_comment

0 Comments


*  loading

Â 
Â 
Â 
Â 
Â 


          _free_counters_


Imprint | _druckversion_print_version | Sitemap
 Jimdo_logout | Edit
