#+TITLE:    Deep Inside - OSPDM5
#+AUTHOR:    
#+EMAIL:     
#+DATE:      
#+DESCRIPTION: Deep Inside - OSPDM5 Strategy Guide by JCK
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT: 

* OSPDM5 Strategy Guide /by JCK/
  Very well-arranged map. As with many others, timing and coordination are
  what counts most here.
  There is only one powerup on this map so every unused opportunity to
  grab the Quad may lead a team it to its doom.
  It can be played in different ways, I'll try to show some tips and tricks :-) 

* Items Available
** Weapons
- 2 Shotgun (SG)
- 1 Railgun (RG)
- 1 Grenade Launcher (GL)
- 1 Lightning Gun (LG)
- 2 Rocket Launcher (RL)
- 1 Plasma Gun (PG)
  
** Armors
- 1 Red Armor (RA)
- 2 Yellow Armor (YA)
- 7 Shards
- 1 Mega Health (MH)
- 1 50Health
- 13 25 Health


** Powerups
- Quad Damage

* Railgun

It is good to check for railgun and megahealth (the person who checks it
should only collect shards and mega-health), the enemies are vulnerable easily
and they cannot endanger you at a distance. I advise you to go for the mega-
health few seconds in advance and look around so there is no enemy hidden
there. Shortly before Quad-time it is recommended that two players secure the
railgun as shown on the picture below.

You must pay attention to sound, especially sound which comes from the
jumppad  - and you have to secure the entrance into which the enemies from RA may jump into.

* Quad
 
Immediately before the Quad spawns, it is ideal that your team takes the positions shown on the picture
below, but this isn't always possible. 

** Positions
- Position 1 is a RG boy; he looks after the RG for his colleagues so they can have
it and shoots at distance to secure the railgun and megahealth.
 
- Position 2 is quite difficult; the difficulty depends on how you
  play it. An important task is to always know the exact time of RA
  and MH and maybe even YA. Shortly before Quad the one on position 2 secures the
  teammate on position 1.
 
- Position 3 secures the jumppad and the entrance from YA, apart from
  this, he checks the situation in the central room and makes his
timings for both YA or the MH.
 
- Position 4 gives a helping hand to number two and three; it depends on where the bulk
of enemies is.

 
* WTF? QUAD LOST! CENTRAL & RA ROOM

It is usual in ospdm5 that the position at railgun is frequently exchanged.
Therefore, it is important to keep your head cool and start from
scratch what is in the RA room in this case. Pay attention mainly to
LG and RA; eventually, you can try and get MH sometimes. You can attack the quad directly with RA  - but
be very careful as normally you have nothing available to spam the enemy at distance!
 
The picture above depicts the attack on Quad when you don't have the upper hand
at Quad / Railgun. Position No 1 takes care of that the enemy doesn`t  eat RA
or he eventually makes timing for LG (it is good to know the timing of mega as
well). He attacks straight through RA or carefully through jump-pad.  Position
No 2 secures the central room and the situation at quad. No 4 prevailingly
attacks through YA or directly from central room. Position No 3 is quite
complicated as you look after what is going on in the lower part of the
map. Usually he tries to get mega under control; it is good when No 1 gives a
hand at it. He tries to get on quad through the jump-pad or RG. The last
position No 4 must have in grasp over
those two YA, he attacks mainly through the upper YA
(it is usually effective in combination with a rocket-jumpJ) along with No 2.
