











* Wall
* Quakelive_Bible



Presence. (Remaining in the moment to maximize mental efficiency) *by chance

Presence is the state of mind (or no-mind) that has no past or future. Without
past and future, you are not wasting your brain cells/neurons on things that do
not currently exist and therefore hold no bearing on you as a player. You are
focused entirely on what is happening, and since what is happening is all there
is, it is therefore all that matters. This is an easy way "cut down" or lean up
your thoughts and become all killer, no filler. In my experience, you are may
only compete at your peak performance when you are committed fully to the
present moment. The ideal way to look at this is; there is no seperation
between you and what is. This "oneness" is commonly referred to by sports
analysts as, "the zone." Disciplined presence means we should be playing the
entire game in the moment as it emerges unto itself.

You don't need to "think" to strafe jump. You just do it, and the more you can
clear up the mental noise in your head while you play - the more your mind will
wrap around the task you're trying to accomplish. The task of discipline is
greatly simplified by just maintaining continual conscious presence. How is
this achieved? Focus on the task at hand, nothing more, nothing less - and not
so much on the task, but the totality of the moment.

Your mind should be like water, ready to adapt perfectly to fit any container.
Concentrate on what is happening, what the situation needs from you, don't
think it out in long-drawn inner dialogue - just be aware of it and allow it to
come through you. Give your mind the space and freedom to gather all the
information you need. Allow yourself to respond to the situation with
relentless indifference, clarity. Through this comes power. This is natural for
a lot of athletes but will take some practice in itself if you're not used to
it. It seems like focusing on the "Now" is common sense, but that all depends
on how aware you are of your straying thoughts and emotions. There's not much
more that I can say about this, you either get it or you don't. If you don't,
just keep playing with a clear head and always focus. Eventually you'll figure
out how to find your "zone." When you do, recognize the Presence and understand
that it is an enormously beneficial ability which can become absolutely pivitol
to your success as a player.

Alright, so. Now we know we need discipline to continually bring our best
forward so we can call on our abilities at will, and we know how to stay in the
moment so we can be efficient with our mental resources. The line between beast
and newbie doesn't stop at staying focused and cognatively present the entire
time, you have to be focused on the right things. Now, what exactly are these
"right things" I keep mentioning, the "important stuff"? What should I
concentrate on while I play?
Â 
source www.myeg.net

* Introduction
* Discipline
* Presence
* Opponent_Awareness/Enemy_Status.
* Resource_Timing
* Aim
* Motivation,_Attitude
* Resolve.
* DM14_-_Grim_Dungeons
* OSPDM5_-_Deep_Inside
* Unity's_personal_guide

Â 
Â 
Â 
Â 
Â 


          _free_counters_


Imprint | _druckversion_print_version | Sitemap
 Jimdo_logout | Edit
