











* Wall
* Quakelive_Bible



Resolve. (Conscious adaptation) *by chance

Alright, so I'm practicing really hard and I'm paying acute attention to
everything thats happening - but I still having troubles with such-and-such
problem(s). This is where resolve comes in. Resolve is my favorite word, it
just means so much (seriously, it has 18 definitions on dictionary.com.) I said
at the beginning of this article that discipline may be the most important
aspect of an individuals ability, to me resolve plays a key just above that.
Resolve gives you the ability to take a step back, and tackle the problem again
from a different angle. Or maybe just tackle it harder this time. Or maybe lets
try diving in on it from above. What if we dug a hole and trapped the problem
in a pit of spikes? No, I've got it... we'll use magnets!... haha

A brilliant player (you know who you are) once told me repeatedly to think
outside the box. I kept thinking to myself, "What does that even mean?" I think
the answer to that question, or any question, is the fruit of resolve. With
your resolve you have ability to adapt, rework, recreate, restore, regenerate,
renew. Resolve is the forge by which the blade of your will is tempered. And
like any great sword, it must be shaped, heated, cooled, and folded thousands
of times before it is perfect - but who is ever perfect?
Â 
The end.
The en
I want to remind you that while all these insights are important, and though
its important to gather new knowledge - the core of your concentration while
playing should be on enemy status, and timing. These two components are the
basis for all in-game decision making.

Hopefully this article has given you some knew knowledge or at least a fresh
perspective on things. If you still find yourself getting stuck, try writing
stuff down, you can build a journal or progress report of sorts this way.

It's been fun sharing with you all! Keep at it and together we will improve the
meta game! See you on the interwebs =]
Write_a_comment

0 Comments


*  loading


* Introduction
* Discipline
* Presence
* Opponent_Awareness/Enemy_Status.
* Resource_Timing
* Aim
* Motivation,_Attitude
* Resolve.
* DM14_-_Grim_Dungeons
* OSPDM5_-_Deep_Inside
* Unity's_personal_guide

Â 
Â 
Â 
Â 
Â 


          _free_counters_


Imprint | _druckversion_print_version | Sitemap
 Jimdo_logout | Edit
