











* Wall
* Quakelive_Bible



Aim (The most overthought skill in Quake.) *by chance

If you were to ask the best aimer in the world how he aims so good he would
probably explain the process in a way that would leave you just as well off as
if he told you to tap your heals together and wish for good aim. Indeed, the
concept of "aiming well" is one place where things get a little foggy for us
humans to describe =]. We tend to try to quantify things in order to understand
them and aim is such a dynamic category we are stuck with a lack of general
insight here. But there are a few things that I think play a crucial role in
aim.

1. Comfortablility. Firstly, you needÂ  to be comfortable with your
environment. If you're not used the height of your chair, size of the monitor,
shape of your mouse etc. you may have trouble aiming just because you'll be
encumbered with discomfort the whole game. Simple ^_^. Next you need a
sensitivity you can stand behind 100 percent.Â  To do this, you need it to meet
the demands of the arena with absolute ease and comfort. This means setting it
high enough for those quick yet important placement shots, and having it low
enough to maintain a steady track.

Warmup is there purely to get a good comfortable feel for your setup and make
your mind comfortable with your sensitivity and the general handling of your
mouse again.

2. Concentration. I've said enough on this already. Presence directly equates
to amazing aim =]

3. Movement. Great movement kills two birds with one stone. You stand where you
need to be to simplify the shot(s) while synonymously avoiding enemy attacks.
Â 
These are really the only three factors of any relevance that I can offer you
when it comes to aiming. A lot of people get borderline superstitious with
their aim. Some will nervously tweak mouse settings, sensitivities, visual
configs like they have obsessive compulsive disorder. Don't be that guy ;p.

Here's a few more tips to make sure you're on the right track.

Stop trying to predict the future. There's a lot of hype in being able to
"read" your opponent. Thats fine, but don't mistake "reading" them for
predicting them. You can not predict what a person will do. Trying to predict
player movement in battle will only lead to poor accuracy and frustration. What
you can do is merely read their movements and this'll be all you need to match
them perfectly. So stop spamming that corner for 10 seconds cause he's already
behind you :p. In a straight up shaft fight you want your crosshair to track
the opponent with the immediacy of a shadow (<3 Bruce Lee), and you can only
achieve this through total presence.

Just like we discussed earlier with enemy status, putting yourself in the right
situation with aim also has an enormous value. You're not going to miss that
jump pad shot when you're 200/200 and have every item in the map on lock. The
reason? Comfortability and simplicity. You're comfortable because you're in the
exact situation you need to be, add that to the fact that the shot is the
simplest shot in the game and probably doesn't even require you to move - and
you have yourself a winner :)
Â 
source www.myeg.net
Write_a_comment

0 Comments


*  loading


* Introduction
* Discipline
* Presence
* Opponent_Awareness/Enemy_Status.
* Resource_Timing
* Aim
* Motivation,_Attitude
* Resolve.
* DM14_-_Grim_Dungeons
* OSPDM5_-_Deep_Inside
* Unity's_personal_guide

Â 
Â 
Â 
Â 
Â 


          _free_counters_


Imprint | _druckversion_print_version | Sitemap
 Jimdo_logout | Edit
